# Generated by Django 3.2.6 on 2023-05-03 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myjoinedtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_serial_number', models.CharField(max_length=100)),
                ('valve_size_in', models.IntegerField()),
                ('valve_rating', models.IntegerField()),
                ('valve_manufacturer', models.CharField(max_length=100)),
                ('seattest_result', models.CharField(max_length=100)),
                ('shelltest_result', models.CharField(max_length=100)),
                ('backtest_result', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ValveDetails',
            fields=[
                ('valvedetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('valve_serial_number', models.CharField(max_length=25, unique=True)),
                ('valve_size_in', models.CharField(max_length=255)),
                ('valve_size_dn', models.IntegerField()),
                ('valve_rating', models.IntegerField()),
                ('valve_manufacturer', models.CharField(max_length=255)),
                ('valve_item_code', models.CharField(max_length=255)),
                ('valve_type', models.CharField(max_length=255)),
                ('valve_seat_type', models.CharField(max_length=255)),
                ('valve_end_connection', models.CharField(max_length=255)),
                ('valve_operator', models.CharField(max_length=255)),
                ('valve_bore_type', models.CharField(max_length=255)),
                ('valve_seat_material', models.CharField(max_length=255)),
                ('valve_body_material', models.CharField(max_length=255)),
                ('valve_obturator_material', models.CharField(max_length=255)),
                ('valve_stem_material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ValveReceipt',
            fields=[
                ('valvereceipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('camserv_tagnumber', models.CharField(max_length=100)),
                ('valve_serial_number', models.CharField(max_length=100)),
                ('box_number', models.CharField(max_length=100)),
                ('received_date', models.DateField()),
                ('comments', models.TextField(max_length=100)),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management_app.valvedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ValvePreservation',
            fields=[
                ('valvepreservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('valve_serial_number', models.CharField(max_length=100)),
                ('preservation_codes', models.CharField(max_length=100)),
                ('preservation_date', models.DateField()),
                ('preservation_by', models.CharField(max_length=100)),
                ('comments', models.TextField(default='None', max_length=200)),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management_app.valvedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ValveInspection',
            fields=[
                ('valveinspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('valve_serial_number', models.CharField(max_length=100)),
                ('inspection_codes', models.CharField(max_length=100)),
                ('inspected_date', models.DateField()),
                ('inspected_by', models.CharField(max_length=100)),
                ('issues_identified', models.TextField(max_length=200)),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management_app.valvedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ValveDispatch',
            fields=[
                ('valvedispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('camserv_tagnumber', models.CharField(max_length=100)),
                ('valve_serial_number', models.CharField(max_length=100)),
                ('box_number', models.CharField(max_length=100)),
                ('dispatch_date', models.DateField()),
                ('comments', models.TextField(max_length=100)),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management_app.valvedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ShellTest',
            fields=[
                ('shelltest_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_medium', models.CharField(max_length=100)),
                ('test_pressure', models.IntegerField()),
                ('test_duration', models.IntegerField()),
                ('gauge_serial_number', models.CharField(max_length=100)),
                ('test_requirements', models.CharField(max_length=100)),
                ('allowable_leak_rate', models.IntegerField()),
                ('recorded_leak_rate', models.IntegerField()),
                ('test_date', models.DateField()),
                ('test_result', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, max_length=100, null=True)),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management_app.valvedetails')),
            ],
        ),
        migrations.CreateModel(
            name='SeatTest',
            fields=[
                ('seattest_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_medium', models.CharField(max_length=100)),
                ('test_pressure', models.FloatField()),
                ('test_duration', models.IntegerField()),
                ('gauge_serial_number', models.CharField(max_length=100)),
                ('test_requirements', models.CharField(max_length=100)),
                ('allowable_leak_rate', models.CharField(max_length=100)),
                ('seat_a_rlr', models.CharField(max_length=100)),
                ('seat_b_rlr', models.CharField(max_length=100)),
                ('seat_c_rlr', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_d_rlr', models.CharField(blank=True, max_length=100, null=True)),
                ('test_date', models.DateField()),
                ('test_result', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, max_length=100, null=True)),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management_app.valvedetails')),
            ],
        ),
        migrations.CreateModel(
            name='BackSeatTest',
            fields=[
                ('backseattest_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_medium', models.CharField(max_length=100)),
                ('test_pressure', models.IntegerField()),
                ('test_duration', models.IntegerField()),
                ('gauge_serial_number', models.CharField(max_length=100)),
                ('test_requirements', models.CharField(max_length=100)),
                ('allowable_leak_rate', models.IntegerField()),
                ('recorded_leak_rate', models.IntegerField()),
                ('test_date', models.DateField()),
                ('test_result', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, max_length=100, null=True)),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management_app.valvedetails')),
            ],
        ),
    ]
