# Generated by Django 3.2.6 on 2023-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valvedetails',
            name='valve_serial_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
