# Generated by Django 3.2.6 on 2023-05-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0005_alter_valvedetails_valve_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valveinspection',
            name='valve_serial_number',
        ),
        migrations.RemoveField(
            model_name='valvepreservation',
            name='valve_serial_number',
        ),
    ]
