# Generated by Django 3.2.6 on 2023-05-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0006_auto_20230510_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valvedispatch',
            name='valve_serial_number',
        ),
        migrations.RemoveField(
            model_name='valvereceipt',
            name='valve_serial_number',
        ),
    ]
